name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - v**.**
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./make.sh

    - name: "Upload ISO"
      uses: actions/upload-artifact@v4
      with:
        name: sed-manager-pba
        path: |
          ${{ github.workspace }}/build/sed-manager-pba.iso
        if-no-files-found: error